version: "3.8"

services:
  api-gateway:
    # build:
    #   context: ./api-gateway
    #   dockerfile: Dockerfile
    #   target: base
    # container_name: api-gateway
    image: andratommmm/api-gateway:base.1.0
    volumes:
      - ./api-gateway/src:/app/src
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - mynet
  backend-auth:
    image: andratommmm/backend-auth:base.1.0
    volumes:
      - ./backend-auth/src:/app/src
    expose:
      - "8001"
    ports:
      - "8001:8001"
    networks:
      - mynet
  backend-drawings-in-progress:
    image: andratommmm/backend-drawings-in-progress:base.1.0
    volumes:
      - ./backend-drawings-in-progress/src:/app/src
    expose:
      - "8002"
    ports:
      - "8002:8002"
    networks:
      - mynet
  backend-drawings:
    image: andratommmm/backend-drawings:base.1.0
    volumes:
      - ./backend-drawings/src:/app/src
    expose:
      - "8003"
    ports:
      - "8003:8003"
    networks:
      - mynet
  backend-users:
    image: andratommmm/backend-users:base.1.0
    volumes:
      - ./backend-users/src:/app/src
    expose:
      - "8004"
    ports:
      - "8004:8004"
    networks:
      - mynet
  backend-comments:
    image: andratommmm/backend-comments:base.1.0
    volumes:
      - ./backend-comments/src:/app/src
    expose:
      - "8005"
    ports:
      - "8005:8005"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
