### FOR TESTING
FROM node:20 as base

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install app dependencies
COPY package.json /app
COPY yarn.lock /app
RUN yarn

# Bundle app source
COPY . /app
RUN yarn build

# set args
ENV MONGO_AUTH=mongodb+srv://general:S5GANK3iobHnzvF8@drawing.wvoxhls.mongodb.net/drawings?retryWrites=true&w=majority
ENV PORT=8002
ENV SPACES_ACCESS_KEY=DO00KXHTXKTZJR3DK2N8
ENV SPACES_SECRET_KEY=g92AoaxwWG/7tNKp6+CYOlgEwUe+oCTWvs0qW3k/yAU

CMD [ "yarn", "serve" ]

### FOR PROD
FROM base as production

# compile TS and put into that build folder in container
RUN yarn run build

CMD [ "yarn", "start" ]